import React from 'react';

const About = () => {
  return (
    <section id="about" className="about-section">
      <h2>À propos de moi</h2>
      <p>Je m'appelle Lola et je suis un développeur spécialisé en React et Node.js. J'ai une passion pour le développement web et le design d'interfaces intuitives.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sem odio, porta sit amet mattis ut, rhoncus ut odio. Aliquam erat volutpat. Cras sagittis vel arcu sit amet porta. In fringilla ipsum porta ipsum ultricies, nec commodo ligula egestas. Duis risus nisi, commodo vitae molestie vel, tristique ac lectus. Ut convallis augue augue, non posuere est condimentum sit amet. Sed non metus est. Duis in magna est. Nullam sagittis dignissim lorem a tristique. Ut id dolor et lorem sollicitudin blandit at non lectus. Sed auctor lorem eu leo fringilla, sed imperdiet justo placerat. Phasellus tincidunt tincidunt mauris et finibus. Aenean ac ultricies justo. Maecenas fermentum eleifend nisl, vitae sodales dolor posuere eget.

Maecenas a pellentesque libero, eu tincidunt metus. Vivamus pellentesque efficitur arcu, vitae euismod dui iaculis quis. Morbi ornare ornare feugiat. Praesent id eros leo. Maecenas bibendum sit amet sem ac efficitur. Integer bibendum, dui vitae finibus malesuada, ex velit vehicula neque, hendrerit mollis lectus velit a metus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur sed lorem nec risus viverra venenatis. Duis molestie pulvinar odio, non iaculis eros efficitur at. Aenean tempor rutrum varius. Fusce vehicula lorem ac leo aliquam, ut consequat nisi elementum. Pellentesque ac tempus ex.

Pellentesque leo tortor, sodales ut urna sit amet, semper ornare risus. Suspendisse sed rhoncus urna, ac pharetra ligula. Morbi et ullamcorper sem. Vivamus tincidunt viverra elit sit amet tincidunt. Cras sapien mi, rhoncus nec nibh ac, euismod blandit odio. Duis dictum nec tellus eget cursus. Integer interdum rhoncus massa, a venenatis mauris. Morbi ut porta augue. Pellentesque tempor nunc felis, condimentum hendrerit elit imperdiet in.

Aliquam interdum mattis auctor. Donec ornare augue sed dolor vulputate, eget tempor augue mattis. Morbi id porttitor quam. Fusce elementum velit non egestas posuere. Nulla et sem tortor. Phasellus ac enim malesuada, accumsan metus efficitur, venenatis augue. Nam posuere dui eget nulla viverra finibus.

Nam venenatis placerat turpis, nec venenatis mauris suscipit vel. Duis iaculis erat enim, id fermentum ligula gravida ac. Praesent tristique dapibus viverra. Aenean porta venenatis laoreet. Donec vestibulum, urna non finibus scelerisque, eros dui euismod magna, in elementum purus lorem eu ex. Donec a facilisis magna, id dignissim dolor. Vivamus feugiat, lorem non semper ullamcorper, quam nunc egestas massa, sed vehicula augue sapien sit amet ex. Donec tristique a massa nec posuere. Morbi mattis lobortis libero, ut consequat nunc bibendum in.

Aliquam ut bibendum mi. Fusce blandit bibendum viverra. Ut iaculis felis quam, a sagittis diam dictum vel. Nulla facilisi. Proin ac malesuada sapien. Morbi interdum justo vestibulum turpis ultrices, sed dignissim nibh feugiat. Cras quis est pharetra, posuere mauris at, condimentum massa. Suspendisse imperdiet, tortor sit amet sodales rutrum, enim sapien varius tortor, in suscipit sapien leo ac nibh. Proin sed hendrerit sem, ut ultricies neque. Aliquam vitae ante nisl. Proin cursus tempus elit a bibendum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris dictum nibh venenatis, tincidunt lorem ut, mollis risus. Cras faucibus ornare nisl, eu blandit est vestibulum eget.

Nulla facilisis, justo eget condimentum iaculis, nunc neque molestie nisl, non aliquet magna tellus nec ligula. Quisque imperdiet malesuada leo, sed placerat nunc rhoncus ac. Aliquam scelerisque porta pellentesque. Duis iaculis neque neque, eu bibendum neque hendrerit non. Etiam venenatis ante pretium ante sagittis, vitae tincidunt leo placerat. In odio ipsum, lobortis id fringilla vitae, accumsan ac purus. Aliquam nec ligula dictum, pretium felis a, accumsan lacus. Integer rhoncus nunc vel semper tristique. Aliquam vel sem pellentesque justo tempor imperdiet ac quis tortor. Nam non mi hendrerit, cursus lectus ut, aliquet felis. Quisque ac venenatis nulla. In hac habitasse platea dictumst. Phasellus vel nibh hendrerit, maximus lorem vitae, viverra purus. Integer facilisis tincidunt lacus eu mollis. Pellentesque eros odio, vestibulum et arcu sed, scelerisque convallis urna.

Curabitur eget nunc vulputate, tempor urna eu, tempor nunc. Aliquam erat volutpat. In hac habitasse platea dictumst. Nunc rhoncus augue in ornare congue. Mauris ante turpis, ultricies at risus at, elementum tincidunt ex. Sed vel blandit nulla, sit amet imperdiet velit. Suspendisse nec nunc id mauris lobortis consectetur ac eget neque. Maecenas vel interdum neque, ut gravida orci. Donec a ligula sed enim condimentum luctus. Duis a sagittis felis. Integer tellus diam, accumsan nec velit in, malesuada auctor nisl. Phasellus sollicitudin, felis non placerat iaculis, enim velit pellentesque purus, non vestibulum mauris turpis id odio. Morbi egestas turpis nec mi pulvinar, eget facilisis tellus suscipit. Sed hendrerit dapibus ligula vel consequat. Sed luctus, urna eu blandit posuere, lacus lorem pretium dui, eget eleifend turpis ex a enim. Suspendisse dui ex, mollis et aliquet non, malesuada sit amet lorem.

Nunc maximus sem vel odio ultricies rutrum nec vel nisi. Proin tellus lacus, gravida lobortis imperdiet ac, ultrices a metus. Nam molestie malesuada sapien, vel rutrum felis laoreet id. Sed non lacus id velit lacinia tempus. Sed pharetra ultrices urna a malesuada. Etiam eleifend et mauris id vulputate. Duis ac elit finibus, convallis sem id, euismod leo. Nam aliquet maximus ultricies. Nam auctor posuere scelerisque. Curabitur convallis vel felis quis placerat. Donec ut iaculis ante. In quis rhoncus nibh. Vivamus consectetur non turpis id dapibus. Morbi dignissim quam pretium arcu feugiat aliquet. Praesent id commodo nisl, eget dignissim metus.

Curabitur nec consectetur est, nec lobortis odio. Nam sit amet rutrum dolor, ac sodales massa. Mauris nulla mauris, dictum a fermentum ac, pretium quis massa. Donec finibus dictum enim in egestas. Nulla eu velit nunc. Morbi feugiat justo lectus, sit amet facilisis felis scelerisque sed. Mauris at ipsum magna. Ut fermentum egestas nulla non hendrerit. Pellentesque fermentum lectus sed nisl tempor, mollis elementum ex maximus. Mauris convallis ante nec velit posuere, ac consequat dui sodales. Aenean consectetur turpis neque, bibendum tincidunt turpis commodo convallis.

Morbi tempor neque sit amet sapien viverra tristique. Etiam vitae sem neque. Donec condimentum ligula eget mollis finibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec magna ullamcorper, porttitor mi non, tristique augue. Mauris lorem arcu, tincidunt non quam id, maximus pharetra nunc. Duis ac scelerisque odio. Ut luctus, nibh ac mattis faucibus, sem lorem ultrices</p>
    </section>
  );
};

export default About;
